const Projects: Project[] = [
    {
        title: 'Project 1',
        thumbnailUrl: '/images/car.webp',
        role: 'Branding & Digital Marketing',
        duration: '3 months',
        providedServices: ['Web Design', 'Web Development', 'SEO'],
        date: '2023-01-01',
        problem: "problem\n\n\ntest",
        solution: 'solution',
        images: ['/images/project1.jpg', '/images/project2.jpg'],
        slug: 'project-1',
        githubUrl: 'https://github.com',
        websiteUrl: 'https://google.com',
        technologies: ['React', 'Tailwind CSS', 'Next.js'],
    }, {
        title: 'Project 1',
        thumbnailUrl: '/images/car.webp',
        role: 'Branding & Digital Marketing',
        duration: '3 months',
        providedServices: ['Web Design', 'Web Development', 'SEO'],
        date: '2023-01-01',
        problem: "problem\n\n\ntest",
        solution: 'solution',
        images: ['/images/project1.jpg', '/images/project2.jpg'],
        slug: 'project-1',
        githubUrl: 'https://github.com',
        websiteUrl: 'https://google.com',
        technologies: ['React', 'Tailwind CSS', 'Next.js'],
    }, {
        title: 'Project 1',
        thumbnailUrl: '/images/car.webp',
        role: 'Branding & Digital Marketing',
        duration: '3 months',
        providedServices: ['Web Design', 'Web Development', 'SEO'],
        date: '2023-01-01',
        problem: "problem\n\n\ntest",
        solution: 'solution',
        images: ['/images/project1.jpg', '/images/project2.jpg'],
        slug: 'project-1',
        githubUrl: 'https://github.com',
        websiteUrl: 'https://google.com',
        technologies: ['React', 'Tailwind CSS', 'Next.js'],
    }, {
        title: 'Project 1',
        thumbnailUrl: '/images/car.webp',
        role: 'Branding & Digital Marketing',
        duration: '3 months',
        providedServices: ['Web Design', 'Web Development', 'SEO'],
        date: '2023-01-01',
        problem: "problem\n\n\ntest",
        solution: 'solution',
        images: ['/images/project1.jpg', '/images/project2.jpg'],
        slug: 'project-1',
        githubUrl: 'https://github.com',
        websiteUrl: 'https://google.com',
        technologies: ['React', 'Tailwind CSS', 'Next.js'],
    },
]

export default Projects;